apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp
        image: wizhubdocker8s/:::::java-app-argo:62
        resources:
          limits: 
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-service
spec:
  type: NodePort
  selector:
    app: myjavaapp
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30000
  